### ISSUE TITLE
Error: Could not find any release named 'latest-version-1-2'.

### ISSUE THREAD

**Issue by timotheecour** [alaviss/setup-nim#7]
refs https://github.com/nim-lang/fusion/pull/75#issue-586188240 and https://github.com/nim-lang/fusion/pull/70#issuecomment-792215472

Run alaviss/setup-nim@0.1.1
Error: Could not find any release named 'latest-version-1-2'. The provided branch (version-1-2) might not be tracked by nightlies, or is being updated.
Error: Process completed with exit code 1.

**Comment by alaviss** [comment]
This is an issue in nightlies: https://github.com/nim-lang/nightlies/runs/2048657903?check_suite_focus=true

Double uploading is spotty at times... I manually published the tag, everything should work now.

I'll have to implement https://github.com/nim-lang/nightlies/issues/49 soon if this sort of issues keep happening.
