### ISSUE TITLE
Bug: Fails when installing nim devel

### ISSUE THREAD

**Issue by tandy-1000** [alaviss/setup-nim#9]
Here's the CI file thats failing:
https://github.com/Listen2gether/Listen2gether.github.io/blob/develop/.github/workflows/web.yml

I've retried the job a couple times, always fails.
https://github.com/Listen2gether/Listen2gether.github.io/runs/5497291894?check_suite_focus=true
```
Run alaviss/setup-nim@0.1.1
Run '/home/runner/work/_actions/alaviss/setup-nim/0.1.1/setup.sh' -o 'nim' 'devel' ''
  '/home/runner/work/_actions/alaviss/setup-nim/0.1.1/setup.sh' -o 'nim' 'devel' ''
  shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
Error: Could not find any release named 'latest-devel'. The provided branch (devel) might not be tracked by nightlies, or is being updated.
Error: Process completed with exit code 1.
```

**Comment by alaviss** [comment]
This is a bug in current Nim nightlies where it could not generate the `latest-` tags used by this action and not a bug of this project.

I'll monitor today's nightlies to see if this remains an issue.

**Comment by alaviss** [comment]
I pushed a commit to nightlies which should fix this issue: https://github.com/nim-lang/nightlies/commit/6c938a8ef42f256f54981c3f6580f60ef02a6c69

Please reopen this issue if it's still failing.

**Comment by tandy-1000** [comment]
Thank you! working now :)
